### ISSUE TITLE
Proper access request to public/private repos

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#1]

**Comment by ahmad88me** [comment]
Resolved

**Comment by dgarijo** [comment]
Security and authorization:
At the moment, OnToology will ask for access to all repositories of a given user. All private and public repositories (you cannot specify which repos you will be giving access due to a limitation in the Github API).
We are going to change this into the following: if the repository is a public repository, then OnToology will ask to access JUST public repositories. If the repository is private, then OnToology will ask for public and private repo access. If an earlier private access permission has been granted, OnToology will keep it.

**Comment by dgarijo** [comment]
Once we do this, we will add a description in the About page of OnToology

**Comment by ahmad88me** [comment]
Fixed
