### ISSUE TITLE
problem with rights

### ISSUE THREAD

**Issue by mariapoveda** [OnToology/OnToology#137]
I added https://github.com/dgarijo/VideoGameOntology then I get a message saying I had no permission to watch that repository but it appears in my list and I can execute commands on it.

**Comment by ahmad88me** [comment]
@mariapoveda I will check why it is giving this issue

**Comment by ahmad88me** [comment]
@mariapoveda this can't be fixed, I contacted GitHub support for that issue and they replied that collaborators to personal repos can't add webhooks. To work around this, you can fork the target repo and then add the forked repo to OnToology. After that since you are a collaborator, you can merge the changes to the original repo

**Comment by mariapoveda** [comment]
ok
