### ISSUE TITLE
I always get errors when deleting repositories / unwatch them

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#224]
I get the error, then the repository is deleted.

**Comment by ahmad88me** [comment]
@dgarijo The error is coming from the APIs, but now it is working I don't know why. So I added more information in the logs to detect future errors.

**Comment by ahmad88me** [comment]
@dgarijo Finally I captured the error, it was due to session variable that got unset/cleared after sometime.  Full explanation is in https://github.com/OnToology/OnToology/issues/228 
Seems like I created another issue with the same description issue #228
so I'll mark this one as duplicate, and it is solved as well ;)
