### ISSUE TITLE
Cannot watch this repo: opencitydata/vocabularios-datos-abiertos

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#53]
I get this error:
TypeError at /get_access_token

cannot concatenate 'str' and 'dict' objects

**Comment by dgarijo** [comment]
Maybe it's because it's a group/organization.
In any case, the error should be more informative than what we currently can see.

**Comment by ahmad88me** [comment]
@dgarijo   Yes it won't work with organization because github does not allow adding collaborators since it works with teams only which can only be done through the admin and cannot not be granted from github API, but once auton is added as collaborator it would work (I guess). I need to test it. But the error is happening in a  code that is only triggered when it is an organization (python error). I need to test it

**Comment by ahmad88me** [comment]
@dgarijo @mariapoveda For using ontoology with organizations, I was able to implement that for ontoology, but the problem is that for organization, adding team member require OnToology github user to accept the invitation manually for each repo.

**Comment by dgarijo** [comment]
That is perfectly fine. We just need to inform the user with that for this particular use case.

**Comment by ahmad88me** [comment]
@dgarijo like a msg telling him that repos under organization is not supported, or it needs a manual acceptance ?

**Comment by dgarijo** [comment]
When the repo is an organization, explain in a page the set of actions that the user has to follow.

**Comment by ahmad88me** [comment]
At the moment as agreed with Daniel, we will have repos under organization not supported for the moment, and will have it as a new feature
